# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Create Release
      uses: ncipollo/release-action@v1.6.1
      with:
        name: latest
        tag: latest
        allowUpdates: true
        prerelease: true
        artifact: "build/libs/*-all.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update latest tag
      uses: richardsimko/update-tag@master
      with:
        tag_name: latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Deploy
      uses: alinz/ssh-scp-action@v0.1.1
      with:
        host: ${{ secrets.DEPLOY_SSH_HOST }}
        user: ${{ secrets.DEPLOY_SSH_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        ssh_before: rm -f ${{ secrets.DEPLOY_SSH_PATH }}/*-all.jar
        scp: "\"build/libs/*-all.jar\" ${{ secrets.DEPLOY_SSH_USER }}@${{ secrets.DEPLOY_SSH_HOST }}:${{ secrets.DEPLOY_SSH_PATH }}/"
        ssh_after: supervisorctl restart fang
        

    
